In [1]:
import numpy as np;

# numpy indexing & slicing of vector

In [4]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[4]

np.int64(15)

In [11]:
print(arr[0:5])
print(arr[:5])

[11 12 13 14 15]
[11 12 13 14 15]


In [13]:
print(arr[:])
print(arr[1::2])

[11 12 13 14 15 16 17 18 19 20]
[12 14 16 18 20]


# numpy indexing & slicing of matrix

In [15]:
arr=np.arange(1,31).reshape(6,5);
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [16]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [17]:
arr[1][0]

np.int64(6)

In [18]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [19]:
arr[3:6,3:6]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [21]:
arr[:,0]

array([ 1,  6, 11, 16, 21, 26])

# boolean indexing

In [22]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
arr[arr%2==0]

array([12, 14, 16, 18, 20])