In [46]:
import numpy as np;

# arithematic operations!!

In [47]:
a1=np.array([1,2,3,4,5])
a2=np.array([5,6,7,8,9])

In [48]:
a1+a2

array([ 6,  8, 10, 12, 14])

In [49]:
a1-a2

array([-4, -4, -4, -4, -4])

In [50]:
a1*a2

array([ 5, 12, 21, 32, 45])

In [51]:
a1/a2

array([0.2       , 0.33333333, 0.42857143, 0.5       , 0.55555556])

In [52]:
a1//a2

array([0, 0, 0, 0, 0])

In [53]:
a1**a2

array([      1,      64,    2187,   65536, 1953125])

# broadcasting!

In [54]:
l=[1,2,3,4,5]
arr=np.array(l)

In [55]:
arr+10

array([11, 12, 13, 14, 15])

In [56]:
arr=np.arange(1,21).reshape(5,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [57]:
arr+1

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

# deep & shallow copy

In [58]:
a=np.arange(1,21)

In [59]:
slice=a[:5]
slice

array([1, 2, 3, 4, 5])

In [60]:
slice+10

array([11, 12, 13, 14, 15])

In [61]:
a                                                 # no change in a 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
b=a                                                            #so always use a.copy() -> fxn to make shallow copy
b[0]=99

In [63]:
print(b)
print(a)

[99  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[99  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [64]:
b=a.copy()
b[1]=20

In [65]:
print(b)
print(a)

[99 20  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[99  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


# matrix operations!

In [66]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [67]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [68]:

print(a @ b)                                               # dot product          ->        @
print(np.dot(a,b))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [69]:
 a.T                                                       # transpose of a matrix     ->    T

array([[1, 3],
       [2, 4]])


# advance array manipulation

In [70]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])

array([[1, 2],
       [3, 4]])

In [72]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [73]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [74]:
np.column_stack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# splitting array

In [81]:
arr=np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [82]:
np.hsplit(arr,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [83]:
np.vsplit(arr,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]