In [4]:
import numpy as np;

arr=np.array([1,2,3,4,5])
print(arr);

[1 2 3 4 5]


In [5]:
arr=[1,2,3,4.4,"hello"]
print(arr);


[1, 2, 3, 4.4, 'hello']


In [10]:
arr1=np.array(arr)
print(arr1,arr1.dtype);               #convert all data to string!

['1' '2' '3' '4.4' 'hello'] <U32


In [11]:
arr=[[1,2,3],[4,5,6],[7,8,9]]
print(arr);

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [14]:
#2d array!!-

arr1=np.array(arr);
print(arr1);



[[1 2 3]
 [4 5 6]
 [7 8 9]]


# array fxn -

In [15]:
arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [19]:
arr=np.zeros((4,5));
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
arr=np.ones((2,3))
arr


array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
arr=np.linspace(1,5,3);
arr


array([1., 3., 5.])

# random generation fxn-

In [25]:
arr=np.random.rand(10);                           #normalisation     -     range[0 to 1]
arr

array([0.16892596, 0.72829518, 0.16285143, 0.95667157, 0.32675416,
       0.48955137, 0.87440673, 0.57316663, 0.0620579 , 0.12460584])

In [26]:
arr=np.random.randn(10);                           #standardization     -     range[-3 to 3]
arr

array([-0.92853103, -0.87503216, -0.89662221,  1.40655415, -0.26373978,
       -1.20426638, -0.17023887,  0.77182404, -1.10634031,  0.69100546])

In [27]:
arr=np.random.randint(1,100,30)                                  # shift + tab      -> to read fxn parameters
arr                                                              # shift + return   -> to run the cell

array([38, 30, 64, 90, 45, 52, 97,  3, 56, 70, 66, 30,  8, 97, 69, 64, 50,
        4, 70, 63,  3, 95, 62, 88, 61, 29,  2, 79, 79, 67])

# array attributes

In [31]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]]);
arr

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [32]:
arr.shape

(3, 3)

In [33]:
arr.size

9

In [34]:
arr.dtype

dtype('int64')

# array methods-

In [52]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]]);
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr.min()

np.int64(1)

In [54]:
arr.max()

np.int64(9)

In [55]:
arr.sum()

np.int64(45)

In [56]:
col=np.sum(arr,axis=0)
col

array([12, 15, 18])

In [57]:
row=np.sum(arr,axis=1)
row

array([ 6, 15, 24])

In [58]:
arr.mean()

np.float64(5.0)

In [59]:
arr.std()

np.float64(2.581988897471611)

In [60]:
arr.argmax()                                       #returns maximum value idx 

np.int64(8)

In [61]:
arr.argmin()                                       #returns minimum value idx

np.int64(0)

# array reshaping & resizing!

In [62]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [64]:

reshaped_arr=arr.reshape(5,6)                                   # |total no of element = matrix product|
reshaped_arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])